import type { Metadata } from "next";
import {Geist, Geist_Mono, Inter} from "next/font/google";
import "./globals.css";
import AppQueryClientProvider from "@/providers/AppQueryClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const InterFont = Inter({subsets: ["cyrillic"]})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${InterFont.className} antialiased`}
      >
        <AppQueryClientProvider>
            <main>
                {children}
            </main>
        </AppQueryClientProvider>
      </body>
    </html>
  );
}
